// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKs1DQDiWlw-DPzK93YGn7WhYOncmgofw',
    appId: '1:427299576615:web:9a48beb7e82650c36ea702',
    messagingSenderId: '427299576615',
    projectId: 'coursebyzee-95860',
    authDomain: 'coursebyzee-95860.firebaseapp.com',
    storageBucket: 'coursebyzee-95860.firebasestorage.app',
    measurementId: 'G-JWWF1C3EHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI4EMOCyxE8XuYwjTLaQzpTGkB3l5RRlM',
    appId: '1:427299576615:android:2fd28b9016937cd86ea702',
    messagingSenderId: '427299576615',
    projectId: 'coursebyzee-95860',
    storageBucket: 'coursebyzee-95860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmgzL2en0kwSvlp7zdiY1Df_BMxmnusY',
    appId: '1:427299576615:ios:9ef2eb693d6353cc6ea702',
    messagingSenderId: '427299576615',
    projectId: 'coursebyzee-95860',
    storageBucket: 'coursebyzee-95860.firebasestorage.app',
    iosBundleId: 'com.attendancezee.attendanceZee',
  );
}
