class AppBadWords {
  static const List<String> badWords = [
    // User's original list
    "2g1c",
    "2 girls 1 cup",
    "acrotomophilia",
    "alabama hot pocket",
    "alaskan pipeline",
    "anal",
    "anilingus",
    "anus",
    "apeshit",
    "arsehole",
    "ass",
    "asshole",
    "assmunch",
    "auto erotic",
    "autoerotic",
    "babeland",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy", "ball kicking", "ball licking", "ball sack", "ball sucking",
    "bangbros", "bangbus", "bareback", "barely legal", "barenaked", "bastard",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips", "beastiality", "bestiality", "big black", "big breasts",
    "big knockers", "big tits", "bimbos", "birdlock", "bitch", "bitches",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "blowjob",
    "blow job",
    "blow your load", "blue waffle", "blumpkin", "bollocks", "bondage", "boner",
    "boob",
    "boobs",
    "booty call",
    "brown showers",
    "brunette action",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bung hole",
    "bunghole",
    "busty",
    "butt",
    "buttcheeks", "butthole", "camel toe", "camgirl", "camslut", "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cialis",
    "circlejerk",
    "clit",
    "clitoris",
    "clusterfuck", "cock", "cocks", "creampie", "cum", "cumming", "cumshot",
    "cumshots",
    "cunnilingus",
    "cunt",
    "deep throat",
    "deepthroat",
    "dick",
    "dildo",
    "doggy style",
    "ejaculation",
    "erotic",
    "escort",
    "fag",
    "faggot",
    "fellatio",
    "fingering",
    "fisting",
    "footjob",
    "fuck",
    "fucking",
    "gangbang",
    "genitals",
    "g-spot", "handjob", "hentai", "hooker", "horny", "incest", "intercourse",
    "jerk off",
    "jizz",
    "kinky",
    "masturbate",
    "masturbation",
    "milf",
    "motherfucker",
    "nude", "nudity", "orgasm", "orgy", "paedophile", "pedophile", "penis",
    "phone sex", "porn", "porno", "pornography", "pussy", "rape", "raping",
    "rapist", "rimjob", "semen", "sex", "sexo", "sexual", "sexually", "shit",
    "slut",
    "smut",
    "sodomy",
    "suck",
    "tits",
    "titty",
    "topless", 
    "twat",
    "vagina",
    "vibrator", "voyeur", "vulva", "wank", "wet dream", "whore", "xxx", "yaoi",
    "zoophilia", "🖕",

    // User's Arabic list
    "سكس",
    "طيز",
    "شرج",
    "لعق",
    "لحس",
    "مص",
    "تمص",
    "بيضان",
    "ثدي",
    "بز",
    "بزاز",
    "حلمة", "بظر", "كس", "فرج", "شهوة", "شاذ", "مبادل", "عاهرة", "جماع", "قضيب",
    "زب", "لوطي", "لواط", "سحاق", "سحاقية", "اغتصاب", "خنثي", "احتلام", "نيك",
    "متناك", "متناكة", "شرموطة", "عرص", "خول", "قحبة", "لبوة",

    // Additional English words
    "abortion",
    "ahole",
    "amcik",
    "andskota",
    "arse",
    "ash0le",
    "ash0les",
    "asholes",
    "ass face",
    "ass monkey",
    "assface",
    "assh0le",
    "assh0lez",
    "assholz",
    "assrammer",
    "asswipe", "b00bs", "b1tch", "bassterds", "bastards", "bitchin", "bitching",
    "bloody", "boffing", "b00b", "breasts", "bugger", "bull shit", "bullshits",
    "buttfuck",
    "buttfucker",
    "buttplug",
    "c0ck",
    "c0cks",
    "c0k",
    "cawk",
    "chink",
    "cipa", "clits", "cockhead", "cockteaser", "coon", "cooter", "crap", "cums",
    "cunts", "cyalis", "cyberfuc", "cyberfuck", "cyberfucked", "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "damm",
    "damn",
    "dickhead",
    "dildos",
    "dink",
    "dinks", "dirsa", "dog-fucker", "donkeyribber", "doosh", "duche", "dyke",
    "ejaculate", "ejaculated", "ejaculates", "ejaculating", "f4gga", "fanny",
    "fanyy", "fatass", "fcuk", "fcuker", "fcuking", "fecal", "felch", "fellate",
    "fingerfuck", "fingerfucks", "fistfuck", "fistfucker", "flange", "fothc",
    "fucked", "fucker", "fuckers", "fuckface", "fuckhead", "fuckin", "fuckings",
    "fuckme", "fucks", "fudge packer", "fudgepacker", "fuk", "fuker", "fuking",
    "fuks", "fukwhit", "fukwitz", "fux", "fux0r", "gay", "gaylord",
    "gaymuthafuckinwhore",
    "gays",
    "goatse",
    "hardcore",
    "hell",
    "hoar",
    "hoare",
    "hoer", "homo", "hore", "horniest", "hotsex", "jackoff", "jap", "jerk-off",
    "jism",
    "jiz",
    "jizm",
    "kawk",
    "knob",
    "knobhead",
    "knobned",
    "kock",
    "kondum",
    "kondums",
    "kum",
    "kumer",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "l3itch",
    "labia", "lust", "lusting", "m0f0", "m0fo", "m45terbate", "ma5terb8",
    "ma5terbate", "masochist", "masterbate", "masterbation", "mof0", "mofo",
    "mothafuck", "mothafucka", "mothafuckas", "mothafuckaz", "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "motherfuck",
    "motherfucked",
    "motherfuckers",
    "motherfuckin", "motherfucking", "motherfuckings", "motherfucks", "muff",
    "mutha", "muthafecker", "muthafuckker", "muther", "mutherfucker", "n1gga",
    "n1gger", "nazi", "nigg3r", "nigg4h", "nigga", "niggah", "niggas", "niggaz",
    "nigger", "niggers", "nob", "nob jokey", "nobhead", "nobjocky", "nobjokey",
    "numbnuts", "nutsack", "orgasim", "orgasims", "orgasms", "p0rn", "pawn",
    "pecker", "penisfucker", "phonesex", "phuck", "phuk", "phuked", "phuking",
    "phukked", "phukking", "phuks", "phuq", "pimp", "piss", "pissed", "pisser",
    "pisses", "pissing", "pissoff", "poop", "pornos", "prick", "pricks", "pron",
    "pube", "pusse", "pussi", "pussies", "pussys", "rectum", "retard", "rimjaw",
    "rimming", "s hit", "sadism", "sadist", "schlong", "screwing", "scroat",
    "scrote",
    "scrotum",
    "sh!t",
    "sh1t",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shemale", "shitdick", "shite", "shited", "shitey", "shitfuck", "shitfull",
    "shithead",
    "shiting",
    "shitings",
    "shits",
    "shitted",
    "shitter",
    "shitters",
    "shitting", "shittings", "shitty", "skank", "sluts", "smegma", "snatch",
    "son-of-a-bitch",
    "spunk",
    "t1tt1e5",
    "t1tties",
    "teets",
    "teez",
    "testical",
    "testicle", "tit", "titfuck", "titt", "tittie5", "tittiefucker", "titties",
    "tittyfuck", "tittywank", "titwank", "tosser", "turd", "tw4t", "twathead",
    "twatty", "twunt", "v14gra", "v1gra", "viagra", "wang", "wanker", "wanky",
    "whoar", "willies", "willy", "xrated",

    // Additional Arabic words
    "منيوك", "منيوكه", "شرموط", "شرموطه", "علق", "مومس", "قحبه",
    "طيزك", "كسك", "زبك", "زبي", "زبو", "زبه", "بضان", "مبضون", "عراص", "معرص",
    "ديوث", "قرن", "خنيث", "مخنث", "تيز", "بزازك", "بزازها", "بزازه",
    "بنيكك", "انيكك", "يتناك", "تتناك", "ابن المتناكه", "ابن الشرموطه",
    "ابن القحبه",
    "ابن العرص",
    "ابن الخول",
    "يا ابن القحبة",
    "كسمك",
    "كوسمك",
    "خخخ",
    "احا",
    "احه",
    "يلعن دينك",
    "يلعن امك",
    "يلعن ابوك",
    "يلعن ابو",
    "زاني",
    "زانية",
    "دعارة",
    "تفشخ",
    "افشخك",
    "مفشوخ",
    "شخاخ",
    "فشخ",
    "خولات",
    "تزغيط",
  ];
}
